#!/usr/bin/env python3
"""Inline js/calendarModel.mjs into soccer_team_app.jsx.

The app is a single JSX file transpiled in the browser with no module loader, so
it cannot import the merge logic at runtime. The module stays the source of
truth and the test target; this script copies it into the JSX between two marker
comments, stripping the `export ` keyword so the declarations become plain
top-level `const`/`function`.

Idempotent: running it twice produces no diff. Exits non-zero when a marker is
missing, so drift is loud rather than silent.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE = ROOT / "js" / "calendarModel.mjs"
TARGET = ROOT / "soccer_team_app.jsx"

BEGIN = "// ── BEGIN calendarModel (generated) ──"
END = "// ── END calendarModel (generated) ──"


def main() -> int:
    if not MODULE.exists():
        print(f"ERROR: source module not found: {MODULE}", file=sys.stderr)
        return 1
    if not TARGET.exists():
        print(f"ERROR: target not found: {TARGET}", file=sys.stderr)
        return 1

    jsx = TARGET.read_text()

    for marker, name in ((BEGIN, "BEGIN"), (END, "END")):
        count = jsx.count(marker)
        if count != 1:
            print(
                f"ERROR: expected exactly 1 {name} marker in {TARGET.name}, found "
                f"{count}.\n       Marker line must be present verbatim: {marker}",
                file=sys.stderr,
            )
            return 1

    begin_at = jsx.index(BEGIN)
    end_at = jsx.index(END)
    if end_at < begin_at:
        print(
            f"ERROR: END marker precedes BEGIN marker in {TARGET.name}.",
            file=sys.stderr,
        )
        return 1

    # Strip the ES-module `export ` keyword; everything else is copied verbatim.
    body = re.sub(r"^export ", "", MODULE.read_text(), flags=re.MULTILINE).strip("\n")

    generated = (
        f"{BEGIN}\n"
        f"// Generated by scripts/inline_calendar_model.py from js/calendarModel.mjs.\n"
        f"// Do not edit here — edit the module and re-run the script.\n"
        f"{body}\n"
        f"{END}"
    )

    updated = jsx[:begin_at] + generated + jsx[end_at + len(END):]

    if updated == jsx:
        print("inline copy already current — no change")
        return 0

    TARGET.write_text(updated)
    print(f"inlined {len(body.splitlines())} lines from {MODULE.name} into {TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
